### ISSUE TITLE
Error trying to connect to Uwazi with UwaziAdapter()

### ISSUE THREAD

**Issue by tanner-ducharme** [huridocs/python_uwazi_API#5]
Recently, my code started raising an error when I try to connect to Uwazi with UwaziAdapter().

As far as I know, nothing in my code was changed between the time when it was functional and when it started failing. 

Also, my uwazi credentials have not been changed.

The error is as follows:

```
Traceback (most recent call last):
  File "post_articles.py", line 307, in <module>
    uploadToUwazi(user, password, template_id, url, df)
  File "post_articles.py", line 143, in uploadToUwazi
    uwazi_adapter = UwaziAdapter(user=user, password=password, url=url)
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi/uwazi_api/UwaziAdapter.py", line 14, in __init__
    self.uwazi_request = UwaziRequest(url, user, password)
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi/uwazi_api/UwaziRequest.py", line 16, in __init__
    self.connect_sid = self.get_connect_sid()
  File "/Users/Tanner1/Desktop/Projects/RightsActionLab/uwazi/uwazi_api/UwaziRequest.py", line 24, in get_connect_sid
    return response.cookies['connect.sid']
  File "/Users/Tanner1/miniconda3/lib/python3.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Users/Tanner1/miniconda3/lib/python3.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='connect.sid', domain=None, path=None"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "post_articles.py", line 314, in <module>
    raise Exception(error)
Exception: "name='connect.sid', domain=None, path=None"
```

The only cause I can think of might have something to do with 2-factor authentication. I first noticed the issue right after I set up 2-factor auth on my account

Any help is greatly appreciated.

Thanks!

@natasha-todi
@pddocs

**Comment by txau** [comment]
@tanner-ducharme seems like a problem with the cookie and the session, so it could well be 2FA. I can't debug this at the moment so I'll you to kindly disable 2FA and try without it to better accurate the problem?

**Comment by tanner-ducharme** [comment]
confirmed, the issue stopped once I disabled 2FA
